export const QUERY_KEYS = {
	CIRCUITS: 'CIRCUITS',
	CIRCUIT: 'CIRCUIT',
	CIRCUIT_NODES: 'CIRCUIT_NODES',
	CIRCUIT_NODE: 'CIRCUIT_NODE',
	CANISTER_STATUS: 'CANISTER_STATUS',
	CIRCUIT_TRACES: 'CIRCUIT_TRACES',
	NODE_CANISTER_ID: 'NODE_CANISTER_ID',
	SAMPLE_DATA: 'SAMPLE_DATA',
	CANDID: 'CANDID'
};
